apiVersion: {{ template "explorer.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "explorer.fullname" . }}
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "explorer.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "explorer.name" . }}
        chart: {{ template "explorer.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
{{- include "explorer.imagePullSecrets" . | indent 6 }}
      initContainers:
      - name: "wait-for-services"
        image: stevenaldinger/docker-k8s-wait-for-it
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: WAIT_FOR_IT
          value: "true"
        - name: WAIT_FOR_PODS
          value: "odoo-postgresql.odoo"
      containers:
      - name: {{ template "explorer.fullname" . }}
        image: {{ template "explorer.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: TZ
          value: "Asia/Singapore"
        - name: POSTGRESQL_HOST
          value: odoo-postgresql
        - name: POSTGRESQL_URL
          value: postgres://hppoc:password@odoo-postgresql-0:5432/fabricexplorer
        - name: POSTGRESQL_USER
          value: hppoc
        - name: POSTGRESQL_PORT_NUMBER
          value: {{ ternary "5432" .Values.externalDatabase.port .Values.postgresql.enabled | quote }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ ternary (include "explorer.postgresql.fullname" .) (printf "%s-%s" .Release.Name "externaldb") .Values.postgresql.enabled | quote }}
              key: {{ ternary "postgresql-password" "db-password" .Values.postgresql.enabled | quote }}
        - name: POSTGRES_DB
          value: fabricexplorer
        - name: DATABASE_HOST
          value: odoo-postgresql
        - name: LOG_LEVEL_APP
          value: debug
        - name: LOG_LEVEL_DB
          value: debug
        - name: LOG_LEVEL_CONSOLE
          value: info
        - name: LOG_CONSOLE_STDOUT
          value: "true"
        - name: DISCOVERY_AS_LOCALHOST
          value: "false"
        {{- if .Values.smtpHost }}
        - name: SMTP_HOST
          value: {{ .Values.smtpHost | quote }}
        {{- end }}
        {{- if .Values.smtpPort }}
        - name: SMTP_PORT
          value: {{ .Values.smtpPort | quote }}
        {{- end }}
        {{- if .Values.smtpUser }}
        - name: SMTP_USER
          value: {{ .Values.smtpUser | quote }}
        {{- end }}
        {{- if .Values.smtpPassword }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "explorer.fullname" . }}
              key: smtp-password
        {{- end }}
        {{- if .Values.smtpProtocol }}
        - name: SMTP_PROTOCOL
          value: {{ .Values.smtpProtocol | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: explorer-data
          mountPath: /bitnami/explorer
        - name: connection
          mountPath: /opt/explorer/app/platform/fabric/connection-profile
        - name: crypto1
          mountPath: /tmp/crypto/peerOrganizations/aptalkarga.tr/users/Admin@aptalkarga.tr/msp/keystore
        - name: crypto2
          mountPath: /tmp/crypto/peerOrganizations/aptalkarga.tr/users/Admin@aptalkarga.tr/msp/signcerts
        - name: crypto3
          mountPath: /tmp/crypto/peerOrganizations/atlantis.com/users/Admin@atlantis.com/msp/keystore
        - name: crypto4
          mountPath: /tmp/crypto/peerOrganizations/atlantis.com/users/Admin@atlantis.com/msp/signcerts
        - name: crypto5
          mountPath: /tmp/crypto/peerOrganizations/nevergreen.nl/users/Admin@nevergreen.nl/msp/keystore
        - name: crypto6
          mountPath: /tmp/crypto/peerOrganizations/nevergreen.nl/users/Admin@nevergreen.nl/msp/signcerts
        - name: crypto7
          mountPath: /tmp/crypto/peerOrganizations/aptalkarga.tr/peers/peer0.aptalkarga.tr/tls
        - name: crypto8
          mountPath: /tmp/crypto/peerOrganizations/atlantis.com/peers/peer0.atlantis.com/tls
        - name: crypto9
          mountPath: /tmp/crypto/peerOrganizations/nevergreen.nl/peers/peer0.nevergreen.nl/tls
        - name: crypto10
          mountPath: /opt/explorer/app/platform/fabric/config.json
          subPath: config.json
        - name: crypto11
          mountPath: /etc/hosts
          subPath: nnn
        
      volumes:
      - name: connection
        configMap:
          name: {{ template "explorer.fullname" . }}-connectionprofile
      - name: crypto1
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto1 
      - name: crypto2
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto2 
      - name: crypto3
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto3 
      - name: crypto4
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto4
      - name: crypto5
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto5
      - name: crypto6
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto6
      - name: crypto7
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto7
      - name: crypto8
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto8
      - name: crypto9
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto9
      - name: crypto10
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto10
      - name: crypto11
        configMap:
          name: {{ template "explorer.fullname" . }}-crypto11
      - name: explorer-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "explorer.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
